# Generated by Django 3.1.7 on 2021-07-06 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('date_created', models.DateField()),
                ('last_update', models.DateTimeField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('Open', 'Open deal'), ('Lost', 'Deal won'), ('Won', 'Deal lost')], default='Open', max_length=20, verbose_name='status')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
