# Generated by Django 3.1.7 on 2021-07-06 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20210706_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
