# Generated by Django 3.1.7 on 2021-07-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_auto_20210706_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
