# Generated by Django 3.1.7 on 2021-07-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_auto_20210706_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('Open', 'Open deal'), ('Lost', 'Deal lost'), ('Won', 'Deal won')], default='Open', max_length=20, verbose_name='status'),
        ),
    ]
